apiVersion: v1
kind: Pod
metadata:
  name: echoname
  namespace: my-namespace
spec:
  containers:
  - name: echo
    image: registry.cluster.wik.cloud/public/echo
    ports:
    - containerPort: 80